from __future__ import annotations

from collections.abc import Iterable
from dataclasses import asdict
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder

from player_state_engine.config import ModelConfig
from player_state_engine.models.quantile import QuantileModelBundle

OPPORTUNITY_STAGES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "participation",
        (
            "opportunity_snap_share",
            "opportunity_route_participation",
            "opportunity_team_plays",
            "opportunity_team_dropbacks",
        ),
    ),
    (
        "volume",
        (
            "opportunity_carry_share",
            "opportunity_target_share",
            "opportunity_red_zone_share",
            "carries",
            "targets",
        ),
    ),
    (
        "conversion",
        (
            "receptions",
            "receiving_yards",
            "rushing_yards",
            "passing_yards",
            "opportunity_total_touchdowns",
        ),
    ),
    ("fantasy", ("fantasy_points_ppr",)),
)


def _classifier_pipeline(frame: pd.DataFrame, features: list[str], config: ModelConfig) -> Pipeline:
    numeric = [column for column in features if pd.api.types.is_numeric_dtype(frame[column].dtype)]
    categorical = [column for column in features if column not in numeric]
    transformers: list[tuple[str, object, list[str]]] = []
    if numeric:
        transformers.append(
            ("numeric", SimpleImputer(strategy="median", add_indicator=True), numeric)
        )
    if categorical:
        transformers.append(
            (
                "categorical",
                Pipeline(
                    [
                        ("impute", SimpleImputer(strategy="most_frequent")),
                        (
                            "encode",
                            OrdinalEncoder(
                                handle_unknown="use_encoded_value",
                                unknown_value=-1,
                                encoded_missing_value=-2,
                            ),
                        ),
                    ]
                ),
                categorical,
            )
        )
    return Pipeline(
        [
            ("preprocess", ColumnTransformer(transformers, remainder="drop")),
            (
                "model",
                HistGradientBoostingClassifier(
                    max_iter=config.max_iter,
                    learning_rate=config.learning_rate,
                    max_leaf_nodes=config.max_leaf_nodes,
                    min_samples_leaf=config.min_samples_leaf,
                    l2_regularization=config.l2_regularization,
                    random_state=config.random_seed,
                ),
            ),
        ]
    )


def _eligible_targets(
    frame: pd.DataFrame, requested: Iterable[str], minimum_rows: int = 25
) -> list[str]:
    targets: list[str] = []
    for target in requested:
        if target not in frame:
            continue
        if pd.to_numeric(frame[target], errors="coerce").notna().sum() >= minimum_rows:
            targets.append(target)
    return targets


class OpportunityHeadBundle:
    """Sequential probabilistic heads for participation, volume and conversion.

    Downstream heads consume upstream *predictions*, not same-week observed
    outcomes. During fitting, upstream inputs are generated by season-wise
    temporal cross-fitting so the ladder does not learn from oracle values.
    """

    def __init__(self, config: ModelConfig | None = None) -> None:
        self.config = config or ModelConfig()
        self.base_features: list[str] = []
        self.active_model: Pipeline | None = None
        self.stage_models: dict[str, QuantileModelBundle] = {}
        self.stage_features: dict[str, list[str]] = {}
        self.stage_targets: dict[str, list[str]] = {}
        self.training_summary: dict[str, object] = {}

    def _crossfit_active(self, frame: pd.DataFrame) -> pd.Series:
        output = pd.Series(np.nan, index=frame.index, dtype=float)
        seasons = sorted(frame["season"].dropna().astype(int).unique())
        for season in seasons[1:]:
            train = frame.loc[frame["season"] < season]
            test = frame.loc[frame["season"] == season]
            if train["opportunity_active"].nunique() < 2 or len(train) < 50:
                continue
            model = _classifier_pipeline(train, self.base_features, self.config)
            model.fit(train[self.base_features], train["opportunity_active"].astype(int))
            output.loc[test.index] = model.predict_proba(test[self.base_features])[:, 1]
        return output

    def _crossfit_stage(
        self,
        frame: pd.DataFrame,
        features: list[str],
        targets: list[str],
    ) -> pd.DataFrame:
        result = pd.DataFrame(index=frame.index)
        seasons = sorted(frame["season"].dropna().astype(int).unique())
        for season in seasons[1:]:
            train = frame.loc[frame["season"] < season]
            test = frame.loc[frame["season"] == season]
            if len(train) < 50:
                continue
            eligible = _eligible_targets(train, targets)
            if not eligible:
                continue
            usable_features = [feature for feature in features if train[feature].notna().any()]
            if not usable_features:
                continue
            model = QuantileModelBundle(self.config).fit(train, usable_features, eligible)
            predicted = model.predict(test, include_context=False)
            predicted.index = test.index
            for target in eligible:
                q50 = f"{target}_q50"
                if q50 in predicted:
                    result.loc[test.index, f"predicted_{target}"] = predicted[q50]
        return result

    def fit(self, frame: pd.DataFrame, base_features: Iterable[str]) -> OpportunityHeadBundle:
        required = {"season", "position", "opportunity_active"}
        missing = required - set(frame.columns)
        if missing:
            raise ValueError(f"Opportunity training frame missing columns: {sorted(missing)}")
        self.base_features = list(base_features)
        if not self.base_features:
            raise ValueError("OpportunityHeadBundle requires at least one pregame feature.")
        data = frame.copy()

        if data["opportunity_active"].nunique() < 2:
            raise ValueError("Active target must contain both active and inactive rows.")
        crossfit_active = self._crossfit_active(data)
        data["predicted_active_probability"] = crossfit_active
        self.active_model = _classifier_pipeline(data, self.base_features, self.config)
        self.active_model.fit(data[self.base_features], data["opportunity_active"].astype(int))

        upstream_features = ["predicted_active_probability"]
        self.stage_models = {}
        self.stage_features = {}
        self.stage_targets = {}
        for stage_name, requested_targets in OPPORTUNITY_STAGES:
            targets = _eligible_targets(data, requested_targets)
            if not targets:
                continue
            features = [*self.base_features, *upstream_features]
            crossfit = self._crossfit_stage(data, features, targets)
            for column in crossfit:
                data[column] = crossfit[column]
            model = QuantileModelBundle(self.config).fit(data, features, targets)
            self.stage_models[stage_name] = model
            self.stage_features[stage_name] = features
            self.stage_targets[stage_name] = targets
            new_upstream = [f"predicted_{target}" for target in targets]
            upstream_features.extend(new_upstream)

        self.training_summary = {
            "rows": int(len(data)),
            "seasons": sorted(int(s) for s in data["season"].unique()),
            "base_feature_count": len(self.base_features),
            "stages": self.stage_targets,
            "crossfit_policy": "train on seasons strictly earlier than held-out season",
        }
        return self

    def predict(self, frame: pd.DataFrame) -> pd.DataFrame:
        if self.active_model is None:
            raise RuntimeError("OpportunityHeadBundle has not been fitted.")
        missing = [feature for feature in self.base_features if feature not in frame]
        if missing:
            raise ValueError(f"Prediction frame is missing base features: {missing[:5]}")
        context = [
            column
            for column in (
                "season",
                "week",
                "game_id",
                "player_id",
                "player_name",
                "recent_team",
                "opponent_team",
                "position",
            )
            if column in frame
        ]
        working = frame.copy()
        output = frame[context].copy().reset_index(drop=True)
        active_probability = self.active_model.predict_proba(working[self.base_features])[:, 1]
        working["predicted_active_probability"] = active_probability
        output["opportunity_active_probability"] = active_probability

        for stage_name, model in self.stage_models.items():
            predicted = model.predict(working, include_context=False)
            for column in predicted:
                output[column] = predicted[column].to_numpy()
            for target in self.stage_targets[stage_name]:
                working[f"predicted_{target}"] = predicted[f"{target}_q50"].to_numpy()
        return output

    def save(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(
            {
                "version": 1,
                "bundle_type": "opportunity_heads",
                "config": asdict(self.config),
                "base_features": self.base_features,
                "active_model": self.active_model,
                "stage_models": self.stage_models,
                "stage_features": self.stage_features,
                "stage_targets": self.stage_targets,
                "training_summary": self.training_summary,
            },
            path,
        )
        return path

    @classmethod
    def load(cls, path: str | Path) -> OpportunityHeadBundle:
        payload = joblib.load(path)
        if payload.get("bundle_type") != "opportunity_heads":
            raise TypeError("Saved model is not an OpportunityHeadBundle.")
        bundle = cls(ModelConfig(**payload["config"]))
        bundle.base_features = payload["base_features"]
        bundle.active_model = payload["active_model"]
        bundle.stage_models = payload["stage_models"]
        bundle.stage_features = payload["stage_features"]
        bundle.stage_targets = payload["stage_targets"]
        bundle.training_summary = payload.get("training_summary", {})
        return bundle
